INSERT INTO PODCAST(ID, TITLE, DESCRIPTION) VALUES (1,'title1', 'description1')
INSERT INTO PODCAST(ID, TITLE, DESCRIPTION) VALUES (2,'title2', 'description2')

INSERT INTO TAG(ID, NAME) VALUES (1,'red')
INSERT INTO TAG(ID, NAME) VALUES (2,'green')

INSERT INTO PODCAST_TAGS(PODCASTS_ID, TAGS_ID) VALUES (1,1)
INSERT INTO PODCAST_TAGS(PODCASTS_ID, TAGS_ID) VALUES (1,2)
INSERT INTO PODCAST_TAGS(PODCASTS_ID, TAGS_ID) VALUES (2,2)